### ISSUE TITLE
Profile grab is missed on startup at random times, OctoFarm doesn't correctly warn the user of this. Seems database is not used as a fallback. 

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1102]
### OctoFarm Version

1.2.9

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Server

### Description of the problem

```markdown
4 OP instances are connected
2 of them didn't appear in the File Manager tab and an error was thrown (attached to end)
```

### Steps taken to reproduce

1. All printers powered and connected
2. Navigated to File Manager, deleted some files
3. Navigated around OF
4. Came back to File Manager, error flagged, 2 printers not listed
5. Navigated to Printers tab, all printers listed, connected and health checks passed
6. Came back to File Manager, error flagged (again), 2 printers not listed

### What did you expect to happen

4x printers to be listed
![Screenshot 2022-06-19 145510](https://user-images.githubusercontent.com/95956617/174469482-8e652189-6da9-4037-be54-9a182757975e.png)
[octofarm_dump-6-19-2022-6-36-32 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8934887/octofarm_dump-6-19-2022-6-36-32.AM.zip)

**Comment by NotExpectedYet** [comment]
Nothing in the logs I could find as to why it wouldn't have this information. There we're some certificate errors but they failed at version grab, and there was a 403 a while back but that's about it. 

I've fixed the client for the next pull so it won't fail without this data. I'll leave this open for a bit just to see if it triggers again. The data was there, and I've nothing that would explicitly remove it so not sure why unless it was just random happenstance but that ain't a good resolution.

**Comment by SuperTrollMan** [comment]
Kind of related:
Seeing it in 1.4.1

![Screenshot 2022-06-23 174648](https://user-images.githubusercontent.com/95956617/175271538-144b992d-a877-4a63-81c3-2c6d91059721.png)

[octofarm_dump-6-23-2022-9-47-12 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8966121/octofarm_dump-6-23-2022-9-47-12.AM.zip)

**Comment by NotExpectedYet** [comment]
Certainly related

**Comment by SuperTrollMan** [comment]
I don't suppose we could have it skip the failing printer and continue to load the remaining working printers?

**Comment by NotExpectedYet** [comment]
> I don't suppose we could have it skip the failing printer and continue to load the remaining working printers?

I'm going to put some better checks and fallbacks in, just didn't have time this morning. Will be working on it tomorrow :). If data not grabbed keep database values, if no database values fail for re-scan.

**Comment by NotExpectedYet** [comment]
I'm "sure" I fixed this so it will close. Just let me know if it hasn't resolved.

**Comment by SuperTrollMan** [comment]
I've tested on 1.5.0, but the issue looks to remain.

Working fine:
![1](https://user-images.githubusercontent.com/95956617/175802955-c3a422b8-60ae-4a58-ad2f-71cd09ac3aeb.png)

Restart server

No tool (due to profile issue)
![2](https://user-images.githubusercontent.com/95956617/175802966-6c3dac9b-1d2a-4aa7-a325-333267cb5e00.png)

Pressing manage > settings and waiting for it to refresh/check settings resolves the issue still.

Secondly, the health checks don't warn in the alerts column of the printers tab.

![3](https://user-images.githubusercontent.com/95956617/175803089-c21e5dec-632d-40c9-8f4b-08c7bda8992f.png)

But health checks does report the issue.

![4](https://user-images.githubusercontent.com/95956617/175803093-ad451b16-769f-4b81-ba8a-ee4af9723f06.png)

Thanks!

**Comment by SuperTrollMan** [comment]
Sorry mate, still doing it for me in 1.5.1
Is there something you need me to do to clear it, or do you want me to leave it so we can keep replicating?
![Screenshot 2022-06-30 181124](https://user-images.githubusercontent.com/95956617/176653955-aaf1f992-4e89-4819-b2e8-b60aeb763d33.png)

**Comment by NotExpectedYet** [comment]
> Sorry mate, still doing it for me in 1.5.1 Is there something you need me to do to clear it, or do you want me to leave it so we can keep replicating? ![Screenshot 2022-06-30 181124](https://user-images.githubusercontent.com/95956617/176653955-aaf1f992-4e89-4819-b2e8-b60aeb763d33.png)

I think you may have to delete and re-add your printer. 

I checked your export and it had all the required database stuff and there's nothing that would stop it loading from that side, and it now uses the database data before hand. If it doesn't resolve after deleting and re-adding let me know and I'll re-open.

**Comment by SuperTrollMan** [comment]
This printer 3 is still having you on by the looks.

**1.6.0** Seems a little worse
Issue remains on file manager tab

New issue: Health Check popup fails to populate, looks like it hangs on it
![Screenshot 2022-08-07 080332](https://user-images.githubusercontent.com/95956617/183270592-ac5613dc-7695-489a-87e1-d8e46182330c.png)

Cant open settings to clear it like previous as it now errors too
![Screenshot 2022-08-07 085829](https://user-images.githubusercontent.com/95956617/183270681-9407452e-ee13-4427-b8f2-676ab4ac997f.png)

[octofarm_dump-8-7-2022-12-59-38 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9275979/octofarm_dump-8-7-2022-12-59-38.AM.zip)

**Comment by SuperTrollMan** [comment]
I was able to temporarily clear it by connecting the printer in OP
Then going to settings in OF, setting again the port and re-saving.
[octofarm_dump-8-7-2022-1-05-05 AM.zip](https://github.com/OctoFarm/OctoFarm/files/9275982/octofarm_dump-8-7-2022-1-05-05.AM.zip)

Will likely return when I restart OF next.

However, its also not honoring the power on delay (which the other printers are), triggering OP to flag this error:
![image](https://user-images.githubusercontent.com/95956617/183270824-189519af-b11a-4fd5-ad8a-ba31a8ca47fe.png)

**Comment by NotExpectedYet** [comment]
There any update with this for V1.6.6? 

I've honestly lost track of it.

**Comment by SuperTrollMan** [comment]
Yep, I can still replicate it in 1.6.6

Time for a new OF instance you think? :P

**Comment by NotExpectedYet** [comment]
I'd see if it fixes it personally. If it does fix it I'm even more confused 😂

**Comment by NotExpectedYet** [comment]
We anywhere else with this? 

I've just not had any other users mention anything regarding the issue for a while. 

Thinking either

The issue is resolved and something is stuck in your instance. 

The issue is with your OctoPrint installation -> failing as card. My API calls are usually the first to go in the situation but not a 100% more a guess. 

The issue is still lurking in the darkness and somehow your triggering it with 1 printer.
